### PR TITLE
heyy

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by KirstieJane** [comment]
Hi @LinaGer94 - at the moment you're asking to merge into the `master` branch, but we need to work in the `gh-pages` branch. Can you change that (I think at the top of this pull request) and let me know when you have so I can merge the request?

Thank you!

**Comment by martintoreilly** [comment]
@LinaGer94 @KirstieJane It looks like this merge request is from the Turing `gh-pages` branch rather than @LinaGer94 's `gh-pages` branch, so I don't think there's anything to merge here. Note that I unprotected the Turing `gh-pages` branch as I couldn't figure out why the student's who had joined the institute couldn't merge PRs even though they had write access.

**Comment by KirstieJane** [comment]
@martintoreilly - I'd missed that these branches were in the same repository. I think we can close this pull request. @LinaGer94 - do you have any questions about what's going on here? Comment below, or find us on slack, if you'd like an explanation!

**Comment by ghost** [comment]
Yeah could you please give an explanation of what you are doing because I missed it

**Comment by KirstieJane** [comment]
Hi @LinaGer94 😺 

If you look at the top of this page, you'll see that you've asked us to merge the information in the Alan Turing Institute's `gh-pages` branch into the Alan Turing Institute's `master` branch.

I think what you meant to submit were changes in *your* `gh-pages` branch (https://github.com/LinaGer94/2017-phd-students/tree/gh-pages) to the Alan Turing Institute's `gh-pages` branch.

It's difficult to update this pull request to change the two branches, so I'd recommend submitting a new pull request which you can do by clicking the "New Pull Request" button on [this page](https://github.com/LinaGer94/2017-phd-students/tree/gh-pages).

Happy to explain further if you'd like, or show you in person next week if that's easier 😃

**Comment by ghost** [comment]
Thank you very much for your immediate reply!  
I would like to make you some more questions;  hence I d be happy to meet you at your convenience next week :)

**Comment by KirstieJane** [comment]
No problem @LinaGer94 - ping me an email at kwhitaker@turing.ac.uk and we can find a time to grab a coffee and take a look side by side (soooo much easier that way!)

**Comment by ghost** [comment]
Sure Kristie :) thanks!

**Comment by KirstieJane** [comment]
Gonna close this - we don't need to update `master` and @LinaGer94 has already added her information in #37 :smile:

**Pull request closed without merging**
