### PR TITLE
Add Julien's info

### PR DESCRIPTION
**Pull request by ghost**
Thank you !

### CODE REVIEW

**Review by c-dickens — APPROVED** [review]
looks good! 👍

**Review by gianlucadetommaso — CHANGES_REQUESTED** [review]
tennsim -> tennis

**Comment by ghost** [comment]
@gianlucadetommaso thank you it is fixed now

**Comment by KirstieJane** [comment]
This all looks great @gianlucadetommaso and @vaesj! Thank you! 🎉

**Pull request merged**
