### PR TITLE
added taha ceritli's profile picture

### PR DESCRIPTION
**Pull request by tahaceritli**

### CODE REVIEW

**Comment by martintoreilly** [comment]
Hi @tahaceritli. We're just reviewing a fix that moves the 200px image width setting up to a single top-level setting rather than duplicated for each person's profile. Please could you remove the "width="200px" attribute from the `td` and `img` tags in preparation for this and I will merge this PR as soon as we merge the above image width setting changes. Thanks.

**Comment by tahaceritli** [comment]
Hi @martintoreilly. Could you make sure that I understand you correctly? 
Do you mean changing td width="200px" to td and img style="width:200px" to img for each person? Or only mine? Thanks.

**Comment by martintoreilly** [comment]
@tahaceritli Please make those changes just for your profile. The image width fix has removed the width attributes for everyone, but your change will be applied afterwards so will overwrite these lines for your profile so we need to make a matching change here.

**Comment by tahaceritli** [comment]
@martintoreilly Is it now fixed?

**Comment by martintoreilly** [comment]
Tested locally so merging

**Comment by martintoreilly** [comment]
@tahaceritli Yes it is. Your picture should be on the site in a few minutes.

**Pull request merged**
